package com.example.demo.user;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import java.util.Collection;
import java.util.Collections;

/*
 * User modal.
 */

// * Lombok annotations
@Getter // Auto generate properties getters.
@Setter // Auto generate properties setters.
@EqualsAndHashCode // Auto generate Equals and HashCode methods for comparing objects.
@NoArgsConstructor // Auto generate an no argument constructor.

//* JPA Annotations
@Entity // Indicates that this class is a JPA entity.

public class User
        implements UserDetails // Add Spring security
{

    /*
     * Define user properties.
     */
    @Id //* JPA Annotation for marking a primary key in this case property id.

    //* JPA for autoincrement.
    @SequenceGenerator(
            name = "user_sequence",
            sequenceName = "user_sequence",
            allocationSize = 1
    )

    // JPA annotation for generating value.
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "user_sequence"
    )

    private Long id;
    private String name, username, email, password;

    //* JPA annotation to specify enum type.
    @Enumerated(EnumType.STRING)
    private UserRole userRole; // Enum
    private Boolean locked, enabled;

    /*
     * Constructors
     */
    //* No arguments constructor generated by lombock.

    public User(
//            Long id, // Ignore if auto generated.
            String name,
            String username,
            String email,
            String password,
            UserRole userRole,
            Boolean locked,
            Boolean enabled) {
        this.name = name;
        this.username = username;
        this.email = email;
        this.password = password;
        this.userRole = userRole;
        this.locked = locked;
        this.enabled = enabled;
    }

    /*
     * Getter and setters for properties or use lombock
     */

    /*
     * Middleware
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        SimpleGrantedAuthority simpleGrantedAuthority =
                new SimpleGrantedAuthority(userRole.name());
        return Collections.singletonList(simpleGrantedAuthority);
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return !locked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }
}
